[default]
src = 'contracts'
out = 'out'
libs = ['node_modules']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@nomiclabs/=node_modules/@nomiclabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@solidity-parser/=node_modules/@solidity-parser/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'ds-test/=lib/ds-test/src/',
]

# See more config options https://github.com/gakonst/foundry/tree/master/config